[swiftformat-0_54_0-darwin]
src.manual = "0.54.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_0-linux-x86_64]
src.manual = "0.54.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_54_1-darwin]
src.manual = "0.54.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_1-linux-x86_64]
src.manual = "0.54.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_54_2-darwin]
src.manual = "0.54.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_2-linux-x86_64]
src.manual = "0.54.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_54_3-darwin]
src.manual = "0.54.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_3-linux-x86_64]
src.manual = "0.54.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_54_4-darwin]
src.manual = "0.54.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_4-linux-x86_64]
src.manual = "0.54.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_54_5-darwin]
src.manual = "0.54.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_5-linux-x86_64]
src.manual = "0.54.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_54_6-darwin]
src.manual = "0.54.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_54_6-linux-x86_64]
src.manual = "0.54.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_0-darwin]
src.manual = "0.55.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_0-linux-x86_64]
src.manual = "0.55.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_1-darwin]
src.manual = "0.55.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_1-linux-x86_64]
src.manual = "0.55.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_2-darwin]
src.manual = "0.55.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_2-linux-x86_64]
src.manual = "0.55.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_3-darwin]
src.manual = "0.55.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_3-linux-x86_64]
src.manual = "0.55.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_4-darwin]
src.manual = "0.55.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_4-linux-x86_64]
src.manual = "0.55.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_5-darwin]
src.manual = "0.55.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_5-linux-x86_64]
src.manual = "0.55.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_6-darwin]
src.manual = "0.55.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_55_6-linux-x86_64]
src.manual = "0.55.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_55_6-linux-aarch64]
src.manual = "0.55.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_56_0-darwin]
src.manual = "0.56.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_56_0-linux-x86_64]
src.manual = "0.56.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_56_0-linux-aarch64]
src.manual = "0.56.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_56_1-darwin]
src.manual = "0.56.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_56_1-linux-x86_64]
src.manual = "0.56.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_56_1-linux-aarch64]
src.manual = "0.56.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_56_2-darwin]
src.manual = "0.56.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_56_2-linux-x86_64]
src.manual = "0.56.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_56_2-linux-aarch64]
src.manual = "0.56.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_56_3-darwin]
src.manual = "0.56.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_56_3-linux-x86_64]
src.manual = "0.56.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_56_3-linux-aarch64]
src.manual = "0.56.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_56_4-darwin]
src.manual = "0.56.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_56_4-linux-x86_64]
src.manual = "0.56.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_56_4-linux-aarch64]
src.manual = "0.56.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_57_0-darwin]
src.manual = "0.57.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_57_0-linux-x86_64]
src.manual = "0.57.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_57_0-linux-aarch64]
src.manual = "0.57.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_57_1-darwin]
src.manual = "0.57.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_57_1-linux-x86_64]
src.manual = "0.57.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_57_1-linux-aarch64]
src.manual = "0.57.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_57_2-darwin]
src.manual = "0.57.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_57_2-linux-x86_64]
src.manual = "0.57.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_57_2-linux-aarch64]
src.manual = "0.57.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_0-darwin]
src.manual = "0.58.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_0-linux-x86_64]
src.manual = "0.58.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_0-linux-aarch64]
src.manual = "0.58.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_1-darwin]
src.manual = "0.58.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_1-linux-x86_64]
src.manual = "0.58.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_1-linux-aarch64]
src.manual = "0.58.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_2-darwin]
src.manual = "0.58.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_2-linux-x86_64]
src.manual = "0.58.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_2-linux-aarch64]
src.manual = "0.58.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_3-darwin]
src.manual = "0.58.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_3-linux-x86_64]
src.manual = "0.58.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_3-linux-aarch64]
src.manual = "0.58.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_4-darwin]
src.manual = "0.58.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_4-linux-x86_64]
src.manual = "0.58.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_4-linux-aarch64]
src.manual = "0.58.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_5-darwin]
src.manual = "0.58.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_5-linux-x86_64]
src.manual = "0.58.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_5-linux-aarch64]
src.manual = "0.58.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_6-darwin]
src.manual = "0.58.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_6-linux-x86_64]
src.manual = "0.58.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_6-linux-aarch64]
src.manual = "0.58.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_7-darwin]
src.manual = "0.58.7"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_7-linux-x86_64]
src.manual = "0.58.7"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_7-linux-aarch64]
src.manual = "0.58.7"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_59_0-darwin]
src.manual = "0.59.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_59_0-linux-x86_64]
src.manual = "0.59.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_59_0-linux-aarch64]
src.manual = "0.59.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_59_1-darwin]
src.manual = "0.59.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_59_1-linux-x86_64]
src.manual = "0.59.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_59_1-linux-aarch64]
src.manual = "0.59.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_60_0-darwin]
src.manual = "0.60.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_60_0-linux-x86_64]
src.manual = "0.60.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_60_0-linux-aarch64]
src.manual = "0.60.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_60_1-darwin]
src.manual = "0.60.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_60_1-linux-x86_64]
src.manual = "0.60.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_60_1-linux-aarch64]
src.manual = "0.60.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"
