[swiftformat-0_58_0-darwin]
src.manual = "0.58.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_0-linux-x86_64]
src.manual = "0.58.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_0-linux-aarch64]
src.manual = "0.58.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_1-darwin]
src.manual = "0.58.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_1-linux-x86_64]
src.manual = "0.58.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_1-linux-aarch64]
src.manual = "0.58.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_2-darwin]
src.manual = "0.58.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_2-linux-x86_64]
src.manual = "0.58.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_2-linux-aarch64]
src.manual = "0.58.2"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_3-darwin]
src.manual = "0.58.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_3-linux-x86_64]
src.manual = "0.58.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_3-linux-aarch64]
src.manual = "0.58.3"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_4-darwin]
src.manual = "0.58.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_4-linux-x86_64]
src.manual = "0.58.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_4-linux-aarch64]
src.manual = "0.58.4"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_5-darwin]
src.manual = "0.58.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_5-linux-x86_64]
src.manual = "0.58.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_5-linux-aarch64]
src.manual = "0.58.5"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_6-darwin]
src.manual = "0.58.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_6-linux-x86_64]
src.manual = "0.58.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_6-linux-aarch64]
src.manual = "0.58.6"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_58_7-darwin]
src.manual = "0.58.7"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_58_7-linux-x86_64]
src.manual = "0.58.7"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_58_7-linux-aarch64]
src.manual = "0.58.7"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_59_0-darwin]
src.manual = "0.59.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_59_0-linux-x86_64]
src.manual = "0.59.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_59_0-linux-aarch64]
src.manual = "0.59.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_59_1-darwin]
src.manual = "0.59.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_59_1-linux-x86_64]
src.manual = "0.59.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_59_1-linux-aarch64]
src.manual = "0.59.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_60_0-darwin]
src.manual = "0.60.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_60_0-linux-x86_64]
src.manual = "0.60.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_60_0-linux-aarch64]
src.manual = "0.60.0"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"

[swiftformat-0_60_1-darwin]
src.manual = "0.60.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat.zip"

[swiftformat-0_60_1-linux-x86_64]
src.manual = "0.60.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux.zip"

[swiftformat-0_60_1-linux-aarch64]
src.manual = "0.60.1"
fetch.url = "https://github.com/nicklockwood/SwiftFormat/releases/download/$ver/swiftformat_linux_aarch64.zip"
