# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swiftformat-0_58_7-darwin = {
    pname = "swiftformat-0_58_7-darwin";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat.zip";
      sha256 = "sha256-fkP44U4gie64PWlYzhYv+pDJMw8/MJygVGk2FLKxskE=";
    };
  };
  swiftformat-0_58_7-linux-aarch64 = {
    pname = "swiftformat-0_58_7-linux-aarch64";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-M8OztNZtF1Exd+Ck+blDYR1koWqhLqUsv7o5WVwJhiE=";
    };
  };
  swiftformat-0_58_7-linux-x86_64 = {
    pname = "swiftformat-0_58_7-linux-x86_64";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat_linux.zip";
      sha256 = "sha256-vhtLt27hNMvGswxVk56ltNvpR8c3PMIBXpcY1LrQCuk=";
    };
  };
  swiftformat-0_60_1-darwin = {
    pname = "swiftformat-0_60_1-darwin";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat.zip";
      sha256 = "sha256-I7UMdfQiPEd+gigzxM+Bmhyau7bQDokpAL2hw6gjGv0=";
    };
  };
  swiftformat-0_60_1-linux-aarch64 = {
    pname = "swiftformat-0_60_1-linux-aarch64";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-4G+2EeIfz2oqC3+bptESo7P4fnprMQ07lc0hXRg6Rzs=";
    };
  };
  swiftformat-0_60_1-linux-x86_64 = {
    pname = "swiftformat-0_60_1-linux-x86_64";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat_linux.zip";
      sha256 = "sha256-wjyxoZkxPQY7GVbp7Ficxl+fYmiEShh1u/ishluN4tk=";
    };
  };
}
