# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  swiftformat-0_54_0-darwin = {
    pname = "swiftformat-0_54_0-darwin";
    version = "0.54.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.0/swiftformat.zip";
      sha256 = "sha256-+Vxo9tdvhLoGvCs1Kg0d+8R+rZF+/VG65VhcKNULxag=";
    };
  };
  swiftformat-0_54_0-linux-x86_64 = {
    pname = "swiftformat-0_54_0-linux-x86_64";
    version = "0.54.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.0/swiftformat_linux.zip";
      sha256 = "sha256-hj6j1jasxVEMqP/Co6KEk4TdHVjVEfKG6DzqgxJnvPQ=";
    };
  };
  swiftformat-0_54_1-darwin = {
    pname = "swiftformat-0_54_1-darwin";
    version = "0.54.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.1/swiftformat.zip";
      sha256 = "sha256-dDnuj9e7E8lshWqXcdcPsrdb8BhzMjIq3Fx3ByUqUf0=";
    };
  };
  swiftformat-0_54_1-linux-x86_64 = {
    pname = "swiftformat-0_54_1-linux-x86_64";
    version = "0.54.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.1/swiftformat_linux.zip";
      sha256 = "sha256-ir4VDJOHm98Oqlks/xuRxgVdFlRt4cnaYpVXIWrAmaM=";
    };
  };
  swiftformat-0_54_2-darwin = {
    pname = "swiftformat-0_54_2-darwin";
    version = "0.54.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.2/swiftformat.zip";
      sha256 = "sha256-uSd1F009DMzmjVRQp2E2cKGNzZEtXEtNrb5bBvBg568=";
    };
  };
  swiftformat-0_54_2-linux-x86_64 = {
    pname = "swiftformat-0_54_2-linux-x86_64";
    version = "0.54.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.2/swiftformat_linux.zip";
      sha256 = "sha256-QJZPDoDLVeXox0Yz15s+uhZqNfyDmqpmsaXyVFcHxbg=";
    };
  };
  swiftformat-0_54_3-darwin = {
    pname = "swiftformat-0_54_3-darwin";
    version = "0.54.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.3/swiftformat.zip";
      sha256 = "sha256-k2d7yK1TBARAs6et6jD3m5+8mXbYd0mWMYl/SjmiQK8=";
    };
  };
  swiftformat-0_54_3-linux-x86_64 = {
    pname = "swiftformat-0_54_3-linux-x86_64";
    version = "0.54.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.3/swiftformat_linux.zip";
      sha256 = "sha256-nD2sIAkt7orIOKBzQG9gxgUIZ0/ETk2dNQVHBIU98jM=";
    };
  };
  swiftformat-0_54_4-darwin = {
    pname = "swiftformat-0_54_4-darwin";
    version = "0.54.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.4/swiftformat.zip";
      sha256 = "sha256-R95eWClouxOIo7vgffwlRSSkEBv0ap3tIqmuzOLAWLg=";
    };
  };
  swiftformat-0_54_4-linux-x86_64 = {
    pname = "swiftformat-0_54_4-linux-x86_64";
    version = "0.54.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.4/swiftformat_linux.zip";
      sha256 = "sha256-N8hsxeEIi23QdloANa4vzizIPcJfQSpMLTaj7p8kyD8=";
    };
  };
  swiftformat-0_54_5-darwin = {
    pname = "swiftformat-0_54_5-darwin";
    version = "0.54.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.5/swiftformat.zip";
      sha256 = "sha256-R8GziLeWlJT2cPHhIzD3SBE2IvZsnh8xacYXXKgHfWc=";
    };
  };
  swiftformat-0_54_5-linux-x86_64 = {
    pname = "swiftformat-0_54_5-linux-x86_64";
    version = "0.54.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.5/swiftformat_linux.zip";
      sha256 = "sha256-Uf09R6MpWdRy0CldGZswq24l4MyvNQ26fE47DvX9ypA=";
    };
  };
  swiftformat-0_54_6-darwin = {
    pname = "swiftformat-0_54_6-darwin";
    version = "0.54.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.6/swiftformat.zip";
      sha256 = "sha256-4Yp3H3KvadTwB9df/3BwVg79f8V6McZnesRDygwf1FI=";
    };
  };
  swiftformat-0_54_6-linux-x86_64 = {
    pname = "swiftformat-0_54_6-linux-x86_64";
    version = "0.54.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.6/swiftformat_linux.zip";
      sha256 = "sha256-pSeocD9dYQgUwz4FRkRDnvJtWGsXWWhHsPW27vwtTFE=";
    };
  };
  swiftformat-0_55_0-darwin = {
    pname = "swiftformat-0_55_0-darwin";
    version = "0.55.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.0/swiftformat.zip";
      sha256 = "sha256-HqEB0E0FcmVo+En8ez0nSr3YE9I0I5Eu6m3BJ7ntHoc=";
    };
  };
  swiftformat-0_55_0-linux-x86_64 = {
    pname = "swiftformat-0_55_0-linux-x86_64";
    version = "0.55.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.0/swiftformat_linux.zip";
      sha256 = "sha256-KdcKFvGzPYFw5t99+suSIunUAIOPj6NeEA2KzaQm/5Y=";
    };
  };
  swiftformat-0_55_1-darwin = {
    pname = "swiftformat-0_55_1-darwin";
    version = "0.55.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.1/swiftformat.zip";
      sha256 = "sha256-nFL1qdHZMO1ehJSJ65q2AZrBloiCCZM+RP859gHR25Q=";
    };
  };
  swiftformat-0_55_1-linux-x86_64 = {
    pname = "swiftformat-0_55_1-linux-x86_64";
    version = "0.55.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.1/swiftformat_linux.zip";
      sha256 = "sha256-+gdkwb5LqXc/AWJr9b5yVGUB/y0VBb7RqKy7QdBXAYg=";
    };
  };
  swiftformat-0_55_2-darwin = {
    pname = "swiftformat-0_55_2-darwin";
    version = "0.55.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.2/swiftformat.zip";
      sha256 = "sha256-i7PsLtG0oT33TXktzK2DNzvY7pU+qG/BqvN1G6k4Q9A=";
    };
  };
  swiftformat-0_55_2-linux-x86_64 = {
    pname = "swiftformat-0_55_2-linux-x86_64";
    version = "0.55.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.2/swiftformat_linux.zip";
      sha256 = "sha256-4ox03NHxYvfEu2CYsu9Fq1E+P5FChSx17B/3/sh/9j4=";
    };
  };
  swiftformat-0_55_3-darwin = {
    pname = "swiftformat-0_55_3-darwin";
    version = "0.55.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.3/swiftformat.zip";
      sha256 = "sha256-xfGP9TkukvrJJ9/a9mAXAJpW+uD29VaR67h4SD9SHSI=";
    };
  };
  swiftformat-0_55_3-linux-x86_64 = {
    pname = "swiftformat-0_55_3-linux-x86_64";
    version = "0.55.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.3/swiftformat_linux.zip";
      sha256 = "sha256-BEvrKEI2SgpR1JC1jp3sJpD8EszmcCSxwE6x3942BN0=";
    };
  };
  swiftformat-0_55_4-darwin = {
    pname = "swiftformat-0_55_4-darwin";
    version = "0.55.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.4/swiftformat.zip";
      sha256 = "sha256-wlK6cQmyR61OFyp6IM7QLw+RMv/fN5yhzY42AnKVCDY=";
    };
  };
  swiftformat-0_55_4-linux-x86_64 = {
    pname = "swiftformat-0_55_4-linux-x86_64";
    version = "0.55.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.4/swiftformat_linux.zip";
      sha256 = "sha256-CsNTNAL7CRrYh3ShEXVINEhRw5v/a6yXRg6X+pV7bnw=";
    };
  };
  swiftformat-0_55_5-darwin = {
    pname = "swiftformat-0_55_5-darwin";
    version = "0.55.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.5/swiftformat.zip";
      sha256 = "sha256-79173oo5iQcNULQfBXRbKvb3cVBvaoMXNRtcF3p+lzI=";
    };
  };
  swiftformat-0_55_5-linux-x86_64 = {
    pname = "swiftformat-0_55_5-linux-x86_64";
    version = "0.55.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.5/swiftformat_linux.zip";
      sha256 = "sha256-wc6ntkkPOYN31tvXb6J0DOdDTB7IA97rrTNnpX0RnQo=";
    };
  };
  swiftformat-0_55_6-darwin = {
    pname = "swiftformat-0_55_6-darwin";
    version = "0.55.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.6/swiftformat.zip";
      sha256 = "sha256-GAwxHRJ8wNAgDXwmHivH/JvT/Jvfx0HRWk2HicZ1qtU=";
    };
  };
  swiftformat-0_55_6-linux-aarch64 = {
    pname = "swiftformat-0_55_6-linux-aarch64";
    version = "0.55.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.6/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-LuaQF0f9t5VXjPhXrr/sYC0lkawi4ZtM3NNgT/82bUo=";
    };
  };
  swiftformat-0_55_6-linux-x86_64 = {
    pname = "swiftformat-0_55_6-linux-x86_64";
    version = "0.55.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.6/swiftformat_linux.zip";
      sha256 = "sha256-oIISSpD0a4f70AEmZvdA4yo5rRxGplCetJDKQ9XLLx4=";
    };
  };
  swiftformat-0_56_0-darwin = {
    pname = "swiftformat-0_56_0-darwin";
    version = "0.56.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.0/swiftformat.zip";
      sha256 = "sha256-FlY/JabP/Nd920aKr4ATIRjeNe/8AP/O1mYHPDxyiQw=";
    };
  };
  swiftformat-0_56_0-linux-aarch64 = {
    pname = "swiftformat-0_56_0-linux-aarch64";
    version = "0.56.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-qJwWz0cE1WRE2hk1uoj5Yy36V7qm4jghZWqCALNYyUk=";
    };
  };
  swiftformat-0_56_0-linux-x86_64 = {
    pname = "swiftformat-0_56_0-linux-x86_64";
    version = "0.56.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.0/swiftformat_linux.zip";
      sha256 = "sha256-HkdaIB/3rtG3ZPQk3OduV87QbcoQzDOWin1Qhx5LqHE=";
    };
  };
  swiftformat-0_56_1-darwin = {
    pname = "swiftformat-0_56_1-darwin";
    version = "0.56.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.1/swiftformat.zip";
      sha256 = "sha256-Sq4yZqEsdmM/Ny3RsLP3UpA32YLyyr++CbfSfBhfSPo=";
    };
  };
  swiftformat-0_56_1-linux-aarch64 = {
    pname = "swiftformat-0_56_1-linux-aarch64";
    version = "0.56.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-7IHpFXKYJjZPhY0r62P9hR75az/LEZNeOJkL0NveIiI=";
    };
  };
  swiftformat-0_56_1-linux-x86_64 = {
    pname = "swiftformat-0_56_1-linux-x86_64";
    version = "0.56.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.1/swiftformat_linux.zip";
      sha256 = "sha256-kR0fOlvxpM+BOSDAVLeyxpgrdkpe3xEram8Ob5JQ+wM=";
    };
  };
  swiftformat-0_56_2-darwin = {
    pname = "swiftformat-0_56_2-darwin";
    version = "0.56.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.2/swiftformat.zip";
      sha256 = "sha256-huEX/+v0A1gb0fxmu5MVyvC5vgSoQVRmzJqOi+9mXj0=";
    };
  };
  swiftformat-0_56_2-linux-aarch64 = {
    pname = "swiftformat-0_56_2-linux-aarch64";
    version = "0.56.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.2/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-6YwKc1vEi81sAbiyqUnKRo12/0a+cZiG57Vh5rnotzo=";
    };
  };
  swiftformat-0_56_2-linux-x86_64 = {
    pname = "swiftformat-0_56_2-linux-x86_64";
    version = "0.56.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.2/swiftformat_linux.zip";
      sha256 = "sha256-y+Gwk5Xnoj+KXzIU4784CWiyiOzhbfmfHAxnp4LW1T4=";
    };
  };
  swiftformat-0_56_3-darwin = {
    pname = "swiftformat-0_56_3-darwin";
    version = "0.56.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.3/swiftformat.zip";
      sha256 = "sha256-TLtjAK+d3KjW22CTgKvev79vOjxHBfiX0/u1oYzna3I=";
    };
  };
  swiftformat-0_56_3-linux-aarch64 = {
    pname = "swiftformat-0_56_3-linux-aarch64";
    version = "0.56.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.3/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-obdD2KMs+RFUbzidj0wQFa28/iMDwrnSsMASSM5k9/A=";
    };
  };
  swiftformat-0_56_3-linux-x86_64 = {
    pname = "swiftformat-0_56_3-linux-x86_64";
    version = "0.56.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.3/swiftformat_linux.zip";
      sha256 = "sha256-N6TRpOLCs58VyjBUW3Ban0Jog0Lcsjn3KwOaJvM/1Pk=";
    };
  };
  swiftformat-0_56_4-darwin = {
    pname = "swiftformat-0_56_4-darwin";
    version = "0.56.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.4/swiftformat.zip";
      sha256 = "sha256-fWaViT6//tjr46RNQEWrVjTqffqo9EiS/BLSGiumIe4=";
    };
  };
  swiftformat-0_56_4-linux-aarch64 = {
    pname = "swiftformat-0_56_4-linux-aarch64";
    version = "0.56.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.4/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-jO0V4OBXu5Y+B38l154qHmGvxH8SFiZaEvvn6X5xzR4=";
    };
  };
  swiftformat-0_56_4-linux-x86_64 = {
    pname = "swiftformat-0_56_4-linux-x86_64";
    version = "0.56.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.56.4/swiftformat_linux.zip";
      sha256 = "sha256-mtZQntB96/paoghjdgVvsLZ4G8kGKr91pqHHu9IDLOQ=";
    };
  };
  swiftformat-0_57_0-darwin = {
    pname = "swiftformat-0_57_0-darwin";
    version = "0.57.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.0/swiftformat.zip";
      sha256 = "sha256-lHEb+9H8b12YA32WEcOdDCO4myaY7lvySvUQePriKyU=";
    };
  };
  swiftformat-0_57_0-linux-aarch64 = {
    pname = "swiftformat-0_57_0-linux-aarch64";
    version = "0.57.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-g9zWl3b0zLxEAYJrNGU7R/GmHFQ/seao1n2DR94W+jI=";
    };
  };
  swiftformat-0_57_0-linux-x86_64 = {
    pname = "swiftformat-0_57_0-linux-x86_64";
    version = "0.57.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.0/swiftformat_linux.zip";
      sha256 = "sha256-lH6atC9ZzgPiLm9cpPGz3y3OaBKco7P6ON2VPejFzqM=";
    };
  };
  swiftformat-0_57_1-darwin = {
    pname = "swiftformat-0_57_1-darwin";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.1/swiftformat.zip";
      sha256 = "sha256-C8d3/AB1EjILQvO0iC/kDLehsIZZuXV8h4qBXXYFV+8=";
    };
  };
  swiftformat-0_57_1-linux-aarch64 = {
    pname = "swiftformat-0_57_1-linux-aarch64";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-wyq2ZVRjeNu6zS7DsZnDSJJNWt5LzPeaVZcQhiRkBBU=";
    };
  };
  swiftformat-0_57_1-linux-x86_64 = {
    pname = "swiftformat-0_57_1-linux-x86_64";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.1/swiftformat_linux.zip";
      sha256 = "sha256-vvzHaaZCtVNe+Qf6FBpx+FUd0eWgKfdiLglgqyjoqQ0=";
    };
  };
  swiftformat-0_57_2-darwin = {
    pname = "swiftformat-0_57_2-darwin";
    version = "0.57.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.2/swiftformat.zip";
      sha256 = "sha256-gzP+35W1xfBNlmFNIEkyeBnghNzXoPnzjaxZqmBKC3Q=";
    };
  };
  swiftformat-0_57_2-linux-aarch64 = {
    pname = "swiftformat-0_57_2-linux-aarch64";
    version = "0.57.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.2/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-ZVLgimhj6WnXioH5JXv/nwWD1Q1WXq6jF+mnljEsKoQ=";
    };
  };
  swiftformat-0_57_2-linux-x86_64 = {
    pname = "swiftformat-0_57_2-linux-x86_64";
    version = "0.57.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.57.2/swiftformat_linux.zip";
      sha256 = "sha256-z+Lsv9khvXv2gfKlR72c9CzFEvIbQW6qc1Ez5tz+Ydw=";
    };
  };
  swiftformat-0_58_0-darwin = {
    pname = "swiftformat-0_58_0-darwin";
    version = "0.58.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.0/swiftformat.zip";
      sha256 = "sha256-aSC43vY1p8yyB2u2XuQyZqUANXsrbrdKcGqJwpFiDyw=";
    };
  };
  swiftformat-0_58_0-linux-aarch64 = {
    pname = "swiftformat-0_58_0-linux-aarch64";
    version = "0.58.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-vrwfLQ5qPaE3+FRTQrQQgxbXw5svM1PDaddG0cpI0ts=";
    };
  };
  swiftformat-0_58_0-linux-x86_64 = {
    pname = "swiftformat-0_58_0-linux-x86_64";
    version = "0.58.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.0/swiftformat_linux.zip";
      sha256 = "sha256-Q+KodHqC7g6AYCi/qOc2iHnX4HAmxbYgyn6CASK2JBs=";
    };
  };
  swiftformat-0_58_1-darwin = {
    pname = "swiftformat-0_58_1-darwin";
    version = "0.58.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.1/swiftformat.zip";
      sha256 = "sha256-4hfOdaChHkQhBwKNCfSjRGOr6mS4lOiB0URtnQhj8j4=";
    };
  };
  swiftformat-0_58_1-linux-aarch64 = {
    pname = "swiftformat-0_58_1-linux-aarch64";
    version = "0.58.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-uWkh+3PKl46yY2eNaYk1D1BvOd8HJKIzNn6tl7tiw0A=";
    };
  };
  swiftformat-0_58_1-linux-x86_64 = {
    pname = "swiftformat-0_58_1-linux-x86_64";
    version = "0.58.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.1/swiftformat_linux.zip";
      sha256 = "sha256-HvD4J0qibPMrlZFQSsJqizGNIMvUj0o4szgcFaTAjT0=";
    };
  };
  swiftformat-0_58_2-darwin = {
    pname = "swiftformat-0_58_2-darwin";
    version = "0.58.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.2/swiftformat.zip";
      sha256 = "sha256-rPg/YBywiK9aH19pJ57EcKlqDDIvNj/m4/Hu4NpFJ1U=";
    };
  };
  swiftformat-0_58_2-linux-aarch64 = {
    pname = "swiftformat-0_58_2-linux-aarch64";
    version = "0.58.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.2/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-RkfloOkfHHZRIoE+NIYN761cx+0dpScsxh++FzkgbJY=";
    };
  };
  swiftformat-0_58_2-linux-x86_64 = {
    pname = "swiftformat-0_58_2-linux-x86_64";
    version = "0.58.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.2/swiftformat_linux.zip";
      sha256 = "sha256-R45b3gjsTcCaWTAikCsexB6hWCWenOkgi32QpUhssRs=";
    };
  };
  swiftformat-0_58_3-darwin = {
    pname = "swiftformat-0_58_3-darwin";
    version = "0.58.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat.zip";
      sha256 = "sha256-wmjldZ4IkfKZKdHxXWhAf0AXWiNkTyQ7FRz+XMutDYw=";
    };
  };
  swiftformat-0_58_3-linux-aarch64 = {
    pname = "swiftformat-0_58_3-linux-aarch64";
    version = "0.58.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-G8bRlrULXM9KzPY/K5lEMb209youNBxK3zerO059NsM=";
    };
  };
  swiftformat-0_58_3-linux-x86_64 = {
    pname = "swiftformat-0_58_3-linux-x86_64";
    version = "0.58.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat_linux.zip";
      sha256 = "sha256-ApoB2yVc0yHqncknez5cKEn4MeOzKV2nU972R4m6qz0=";
    };
  };
  swiftformat-0_58_4-darwin = {
    pname = "swiftformat-0_58_4-darwin";
    version = "0.58.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.4/swiftformat.zip";
      sha256 = "sha256-oarefBzHOI60rwDg1W2z2xmfFXuqReR5kAJDi00BRU4=";
    };
  };
  swiftformat-0_58_4-linux-aarch64 = {
    pname = "swiftformat-0_58_4-linux-aarch64";
    version = "0.58.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.4/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-CMApZLKB8EznnWdxXy51eCfvd4NG7aHcrGjCXHhKe/w=";
    };
  };
  swiftformat-0_58_4-linux-x86_64 = {
    pname = "swiftformat-0_58_4-linux-x86_64";
    version = "0.58.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.4/swiftformat_linux.zip";
      sha256 = "sha256-rud6cwH+OjgIk+t/sAvUizWmKHikKTYA6xczvfG1x9s=";
    };
  };
  swiftformat-0_58_5-darwin = {
    pname = "swiftformat-0_58_5-darwin";
    version = "0.58.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.5/swiftformat.zip";
      sha256 = "sha256-49Weu7qzVn+fRg4tJJg+1E3jUb2AuetbPLFNBjF98Fw=";
    };
  };
  swiftformat-0_58_5-linux-aarch64 = {
    pname = "swiftformat-0_58_5-linux-aarch64";
    version = "0.58.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.5/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-Wdu34A91H4s+vTiEn+1IF4wyE+n8kQe80Rlh6IwuZpM=";
    };
  };
  swiftformat-0_58_5-linux-x86_64 = {
    pname = "swiftformat-0_58_5-linux-x86_64";
    version = "0.58.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.5/swiftformat_linux.zip";
      sha256 = "sha256-+UAqdzZX689sNEZPUB76wykQ9d3+WCdAp4FqK5Gco1c=";
    };
  };
  swiftformat-0_58_6-darwin = {
    pname = "swiftformat-0_58_6-darwin";
    version = "0.58.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.6/swiftformat.zip";
      sha256 = "sha256-QrHgjT2/r5EiSyXfpnX9wx9stec/7oxYywpu5EyU3xg=";
    };
  };
  swiftformat-0_58_6-linux-aarch64 = {
    pname = "swiftformat-0_58_6-linux-aarch64";
    version = "0.58.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.6/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-4TZnm5K+YkW99N8lWAv5uhRKoySQWiV1MVoSCa0X7iw=";
    };
  };
  swiftformat-0_58_6-linux-x86_64 = {
    pname = "swiftformat-0_58_6-linux-x86_64";
    version = "0.58.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.6/swiftformat_linux.zip";
      sha256 = "sha256-SbF93JcnlUAf91rQ0bpdg2qQW5+49D8Y+QUB7pTpXj4=";
    };
  };
  swiftformat-0_58_7-darwin = {
    pname = "swiftformat-0_58_7-darwin";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat.zip";
      sha256 = "sha256-fkP44U4gie64PWlYzhYv+pDJMw8/MJygVGk2FLKxskE=";
    };
  };
  swiftformat-0_58_7-linux-aarch64 = {
    pname = "swiftformat-0_58_7-linux-aarch64";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-M8OztNZtF1Exd+Ck+blDYR1koWqhLqUsv7o5WVwJhiE=";
    };
  };
  swiftformat-0_58_7-linux-x86_64 = {
    pname = "swiftformat-0_58_7-linux-x86_64";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat_linux.zip";
      sha256 = "sha256-vhtLt27hNMvGswxVk56ltNvpR8c3PMIBXpcY1LrQCuk=";
    };
  };
  swiftformat-0_59_0-darwin = {
    pname = "swiftformat-0_59_0-darwin";
    version = "0.59.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.0/swiftformat.zip";
      sha256 = "sha256-pYR9X544u3rP/g6lZTGaUhDmXXIOz2Ke/+ZoKOdyo4c=";
    };
  };
  swiftformat-0_59_0-linux-aarch64 = {
    pname = "swiftformat-0_59_0-linux-aarch64";
    version = "0.59.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-2+1oBdOQ060ffW2JAtyVCJJrHBuTW4oJ0xr+tirp9NI=";
    };
  };
  swiftformat-0_59_0-linux-x86_64 = {
    pname = "swiftformat-0_59_0-linux-x86_64";
    version = "0.59.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.0/swiftformat_linux.zip";
      sha256 = "sha256-ZGlfs5vg2KMoD0aL6jRlK9H3rkILSwQG7lbXtrDtX7E=";
    };
  };
  swiftformat-0_59_1-darwin = {
    pname = "swiftformat-0_59_1-darwin";
    version = "0.59.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.1/swiftformat.zip";
      sha256 = "sha256-i2KJtgikTnPNOFHDWJ29fFU/MsyAWqVLOkls4rkP6+c=";
    };
  };
  swiftformat-0_59_1-linux-aarch64 = {
    pname = "swiftformat-0_59_1-linux-aarch64";
    version = "0.59.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-xVzqNUPdhIiGPRQTL6Z323ZcjwrVpuYYTPgiymJrsds=";
    };
  };
  swiftformat-0_59_1-linux-x86_64 = {
    pname = "swiftformat-0_59_1-linux-x86_64";
    version = "0.59.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.1/swiftformat_linux.zip";
      sha256 = "sha256-FQ2Wk1cM8jTskdigO6cWW9NqeDNcXkDtkeTAE6SS61Q=";
    };
  };
  swiftformat-0_60_0-darwin = {
    pname = "swiftformat-0_60_0-darwin";
    version = "0.60.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.0/swiftformat.zip";
      sha256 = "sha256-j+mq7AM/yZTL8HNm7v+tKWNgHRoOl1R0VGpgbq1uWjk=";
    };
  };
  swiftformat-0_60_0-linux-aarch64 = {
    pname = "swiftformat-0_60_0-linux-aarch64";
    version = "0.60.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-vwT1gfVkNuF9x4t9SrXWiQqYOmpN32AVao6oHl18984=";
    };
  };
  swiftformat-0_60_0-linux-x86_64 = {
    pname = "swiftformat-0_60_0-linux-x86_64";
    version = "0.60.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.0/swiftformat_linux.zip";
      sha256 = "sha256-7IBNETZiBfge0njoUtYV2SFvacD4D+ef5neR5l1G4Bo=";
    };
  };
  swiftformat-0_60_1-darwin = {
    pname = "swiftformat-0_60_1-darwin";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat.zip";
      sha256 = "sha256-I7UMdfQiPEd+gigzxM+Bmhyau7bQDokpAL2hw6gjGv0=";
    };
  };
  swiftformat-0_60_1-linux-aarch64 = {
    pname = "swiftformat-0_60_1-linux-aarch64";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-4G+2EeIfz2oqC3+bptESo7P4fnprMQ07lc0hXRg6Rzs=";
    };
  };
  swiftformat-0_60_1-linux-x86_64 = {
    pname = "swiftformat-0_60_1-linux-x86_64";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat_linux.zip";
      sha256 = "sha256-wjyxoZkxPQY7GVbp7Ficxl+fYmiEShh1u/ishluN4tk=";
    };
  };
}
