# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  swiftformat-0_58_0-darwin = {
    pname = "swiftformat-0_58_0-darwin";
    version = "0.58.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.0/swiftformat.zip";
      sha256 = "sha256-aSC43vY1p8yyB2u2XuQyZqUANXsrbrdKcGqJwpFiDyw=";
    };
  };
  swiftformat-0_58_0-linux-aarch64 = {
    pname = "swiftformat-0_58_0-linux-aarch64";
    version = "0.58.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-vrwfLQ5qPaE3+FRTQrQQgxbXw5svM1PDaddG0cpI0ts=";
    };
  };
  swiftformat-0_58_0-linux-x86_64 = {
    pname = "swiftformat-0_58_0-linux-x86_64";
    version = "0.58.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.0/swiftformat_linux.zip";
      sha256 = "sha256-Q+KodHqC7g6AYCi/qOc2iHnX4HAmxbYgyn6CASK2JBs=";
    };
  };
  swiftformat-0_58_1-darwin = {
    pname = "swiftformat-0_58_1-darwin";
    version = "0.58.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.1/swiftformat.zip";
      sha256 = "sha256-4hfOdaChHkQhBwKNCfSjRGOr6mS4lOiB0URtnQhj8j4=";
    };
  };
  swiftformat-0_58_1-linux-aarch64 = {
    pname = "swiftformat-0_58_1-linux-aarch64";
    version = "0.58.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-uWkh+3PKl46yY2eNaYk1D1BvOd8HJKIzNn6tl7tiw0A=";
    };
  };
  swiftformat-0_58_1-linux-x86_64 = {
    pname = "swiftformat-0_58_1-linux-x86_64";
    version = "0.58.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.1/swiftformat_linux.zip";
      sha256 = "sha256-HvD4J0qibPMrlZFQSsJqizGNIMvUj0o4szgcFaTAjT0=";
    };
  };
  swiftformat-0_58_2-darwin = {
    pname = "swiftformat-0_58_2-darwin";
    version = "0.58.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.2/swiftformat.zip";
      sha256 = "sha256-rPg/YBywiK9aH19pJ57EcKlqDDIvNj/m4/Hu4NpFJ1U=";
    };
  };
  swiftformat-0_58_2-linux-aarch64 = {
    pname = "swiftformat-0_58_2-linux-aarch64";
    version = "0.58.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.2/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-RkfloOkfHHZRIoE+NIYN761cx+0dpScsxh++FzkgbJY=";
    };
  };
  swiftformat-0_58_2-linux-x86_64 = {
    pname = "swiftformat-0_58_2-linux-x86_64";
    version = "0.58.2";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.2/swiftformat_linux.zip";
      sha256 = "sha256-R45b3gjsTcCaWTAikCsexB6hWCWenOkgi32QpUhssRs=";
    };
  };
  swiftformat-0_58_3-darwin = {
    pname = "swiftformat-0_58_3-darwin";
    version = "0.58.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat.zip";
      sha256 = "sha256-wmjldZ4IkfKZKdHxXWhAf0AXWiNkTyQ7FRz+XMutDYw=";
    };
  };
  swiftformat-0_58_3-linux-aarch64 = {
    pname = "swiftformat-0_58_3-linux-aarch64";
    version = "0.58.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-G8bRlrULXM9KzPY/K5lEMb209youNBxK3zerO059NsM=";
    };
  };
  swiftformat-0_58_3-linux-x86_64 = {
    pname = "swiftformat-0_58_3-linux-x86_64";
    version = "0.58.3";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat_linux.zip";
      sha256 = "sha256-ApoB2yVc0yHqncknez5cKEn4MeOzKV2nU972R4m6qz0=";
    };
  };
  swiftformat-0_58_4-darwin = {
    pname = "swiftformat-0_58_4-darwin";
    version = "0.58.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.4/swiftformat.zip";
      sha256 = "sha256-oarefBzHOI60rwDg1W2z2xmfFXuqReR5kAJDi00BRU4=";
    };
  };
  swiftformat-0_58_4-linux-aarch64 = {
    pname = "swiftformat-0_58_4-linux-aarch64";
    version = "0.58.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.4/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-CMApZLKB8EznnWdxXy51eCfvd4NG7aHcrGjCXHhKe/w=";
    };
  };
  swiftformat-0_58_4-linux-x86_64 = {
    pname = "swiftformat-0_58_4-linux-x86_64";
    version = "0.58.4";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.4/swiftformat_linux.zip";
      sha256 = "sha256-rud6cwH+OjgIk+t/sAvUizWmKHikKTYA6xczvfG1x9s=";
    };
  };
  swiftformat-0_58_5-darwin = {
    pname = "swiftformat-0_58_5-darwin";
    version = "0.58.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.5/swiftformat.zip";
      sha256 = "sha256-49Weu7qzVn+fRg4tJJg+1E3jUb2AuetbPLFNBjF98Fw=";
    };
  };
  swiftformat-0_58_5-linux-aarch64 = {
    pname = "swiftformat-0_58_5-linux-aarch64";
    version = "0.58.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.5/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-Wdu34A91H4s+vTiEn+1IF4wyE+n8kQe80Rlh6IwuZpM=";
    };
  };
  swiftformat-0_58_5-linux-x86_64 = {
    pname = "swiftformat-0_58_5-linux-x86_64";
    version = "0.58.5";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.5/swiftformat_linux.zip";
      sha256 = "sha256-+UAqdzZX689sNEZPUB76wykQ9d3+WCdAp4FqK5Gco1c=";
    };
  };
  swiftformat-0_58_6-darwin = {
    pname = "swiftformat-0_58_6-darwin";
    version = "0.58.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.6/swiftformat.zip";
      sha256 = "sha256-QrHgjT2/r5EiSyXfpnX9wx9stec/7oxYywpu5EyU3xg=";
    };
  };
  swiftformat-0_58_6-linux-aarch64 = {
    pname = "swiftformat-0_58_6-linux-aarch64";
    version = "0.58.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.6/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-4TZnm5K+YkW99N8lWAv5uhRKoySQWiV1MVoSCa0X7iw=";
    };
  };
  swiftformat-0_58_6-linux-x86_64 = {
    pname = "swiftformat-0_58_6-linux-x86_64";
    version = "0.58.6";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.6/swiftformat_linux.zip";
      sha256 = "sha256-SbF93JcnlUAf91rQ0bpdg2qQW5+49D8Y+QUB7pTpXj4=";
    };
  };
  swiftformat-0_58_7-darwin = {
    pname = "swiftformat-0_58_7-darwin";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat.zip";
      sha256 = "sha256-fkP44U4gie64PWlYzhYv+pDJMw8/MJygVGk2FLKxskE=";
    };
  };
  swiftformat-0_58_7-linux-aarch64 = {
    pname = "swiftformat-0_58_7-linux-aarch64";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-M8OztNZtF1Exd+Ck+blDYR1koWqhLqUsv7o5WVwJhiE=";
    };
  };
  swiftformat-0_58_7-linux-x86_64 = {
    pname = "swiftformat-0_58_7-linux-x86_64";
    version = "0.58.7";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.7/swiftformat_linux.zip";
      sha256 = "sha256-vhtLt27hNMvGswxVk56ltNvpR8c3PMIBXpcY1LrQCuk=";
    };
  };
  swiftformat-0_59_0-darwin = {
    pname = "swiftformat-0_59_0-darwin";
    version = "0.59.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.0/swiftformat.zip";
      sha256 = "sha256-pYR9X544u3rP/g6lZTGaUhDmXXIOz2Ke/+ZoKOdyo4c=";
    };
  };
  swiftformat-0_59_0-linux-aarch64 = {
    pname = "swiftformat-0_59_0-linux-aarch64";
    version = "0.59.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-2+1oBdOQ060ffW2JAtyVCJJrHBuTW4oJ0xr+tirp9NI=";
    };
  };
  swiftformat-0_59_0-linux-x86_64 = {
    pname = "swiftformat-0_59_0-linux-x86_64";
    version = "0.59.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.0/swiftformat_linux.zip";
      sha256 = "sha256-ZGlfs5vg2KMoD0aL6jRlK9H3rkILSwQG7lbXtrDtX7E=";
    };
  };
  swiftformat-0_59_1-darwin = {
    pname = "swiftformat-0_59_1-darwin";
    version = "0.59.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.1/swiftformat.zip";
      sha256 = "sha256-i2KJtgikTnPNOFHDWJ29fFU/MsyAWqVLOkls4rkP6+c=";
    };
  };
  swiftformat-0_59_1-linux-aarch64 = {
    pname = "swiftformat-0_59_1-linux-aarch64";
    version = "0.59.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-xVzqNUPdhIiGPRQTL6Z323ZcjwrVpuYYTPgiymJrsds=";
    };
  };
  swiftformat-0_59_1-linux-x86_64 = {
    pname = "swiftformat-0_59_1-linux-x86_64";
    version = "0.59.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.59.1/swiftformat_linux.zip";
      sha256 = "sha256-FQ2Wk1cM8jTskdigO6cWW9NqeDNcXkDtkeTAE6SS61Q=";
    };
  };
  swiftformat-0_60_0-darwin = {
    pname = "swiftformat-0_60_0-darwin";
    version = "0.60.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.0/swiftformat.zip";
      sha256 = "sha256-j+mq7AM/yZTL8HNm7v+tKWNgHRoOl1R0VGpgbq1uWjk=";
    };
  };
  swiftformat-0_60_0-linux-aarch64 = {
    pname = "swiftformat-0_60_0-linux-aarch64";
    version = "0.60.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.0/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-vwT1gfVkNuF9x4t9SrXWiQqYOmpN32AVao6oHl18984=";
    };
  };
  swiftformat-0_60_0-linux-x86_64 = {
    pname = "swiftformat-0_60_0-linux-x86_64";
    version = "0.60.0";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.0/swiftformat_linux.zip";
      sha256 = "sha256-7IBNETZiBfge0njoUtYV2SFvacD4D+ef5neR5l1G4Bo=";
    };
  };
  swiftformat-0_60_1-darwin = {
    pname = "swiftformat-0_60_1-darwin";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat.zip";
      sha256 = "sha256-I7UMdfQiPEd+gigzxM+Bmhyau7bQDokpAL2hw6gjGv0=";
    };
  };
  swiftformat-0_60_1-linux-aarch64 = {
    pname = "swiftformat-0_60_1-linux-aarch64";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat_linux_aarch64.zip";
      sha256 = "sha256-4G+2EeIfz2oqC3+bptESo7P4fnprMQ07lc0hXRg6Rzs=";
    };
  };
  swiftformat-0_60_1-linux-x86_64 = {
    pname = "swiftformat-0_60_1-linux-x86_64";
    version = "0.60.1";
    src = fetchurl {
      url = "https://github.com/nicklockwood/SwiftFormat/releases/download/0.60.1/swiftformat_linux.zip";
      sha256 = "sha256-wjyxoZkxPQY7GVbp7Ficxl+fYmiEShh1u/ishluN4tk=";
    };
  };
}
